
version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running build..."
      # Agar aapke project me build script nahi hai to next line comment kar do
      - npm run build || echo "No build step; skipping."
  post_build:
    commands:
      - echo "Preparing deployment package..."
      - mkdir -p bundle
      - cp -r package.json package-lock.json src/ bundle/ || true
      - cp -r dist/ bundle/ || true
      - cp -r scripts/ bundle/ || true
      - cp appspec.yml bundle/
artifacts:
  files:
    - bundle/**/*
  discard-paths: no

